package uz.kundalik.telegram.enums;

public enum UserState {
    NONE,
    DEFAULT,
    AUTHENTICATED,
    AWAITING_LOCATION,

    COMMAND_HELP,
    COMMAND_START,
    COMMAND_DASHBOARD,
    BUTTON_WEATHER,
    BUTTON_PRAYER,
    BUTTON_CURRENCY,
    BUTTON_NOTES,
    BUTTON_REMINDER,
    BUTTON_BIRTHDATE,
    BUTTON_WALLET,
    BUTTON_SETTINGS,


    ;
}
