services:
  prometheus:
    build:
      context: .
      dockerfile: monitoring/prometheus.dockerfile
    container_name: prometheus
    ports:
      - "4001:9090" # Tashqi port 4001, Prometheus ichki porti 9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "4004:3000" # Tashqi port 4004, Grafana ichki porti 3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "4003:3100"
    # `command` qatorini butunlay olib tashlaymiz.
    # Loki endi o'zining standart sozlamalari bilan ishga tushadi.
    restart: unless-stopped

  promtail:
    build:
      context: .
      dockerfile: monitoring/promtail.dockerfile
    container_name: promtail
    volumes:
      - ./logs:/var/log/kundalik
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

volumes:
  grafana-data: