server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kundalik_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    analytics-enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public


  data:
    redis:
      host: ${SERVER_IP}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html


application:
  site:
    backend-base-url: "http://localhost:8080"
    frontend-base-url: "http://localhost:8080"
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

  minio:
    endpoint: ${MINION_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    buckets:
      - kundalik
      - other
      - icons

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    webhook-path: ${TELEGRAM_BOT_PATH}
    chat-id: ${TELEGRAM_CHAT_ID}
    channel-id: ${TELEGRAM_BOT_CHANNEL}

eskiz:
  api:
    url: ${ESKIZ_URL}
    email: ${ESKIZ_EMAIL}
    token: ${ESKIZ_TOKEN}
  sms:
    text: "Sizning tasdiqlash kodingiz: {code}"
  test-mode: true   # 🔥 test rejim da true, production da false
