# src/main/resources/application.yml (LOKAL uchun to'g'ri versiya)

server:
  port: 8080 # Ilovaning asosiy porti
  tomcat:
    redirect-context-root:

spring:
  application:
    name: KUNDALIK

  # Lokal ishlatish uchun 'dev' profilini yoqamiz
  profiles:
    active: ser

  banner:
    location: classpath:banner.txt

# ===================================================================
#   MONITORING & MANAGEMENT CONFIGURATION (ACTUATOR)
# ===================================================================
management:
  server:
    # Lokal uchun kelishilgan port
    port: 4000
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      tomcat: true

# Ilova haqida umumiy ma'lumot
info:
  application:
    name: ${spring.application.name}
    version: @project.version@