server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kundalik_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    analytics-enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public


  data:
    redis:
      host: ${SERVER_IP}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html


application:
  site:
    backend-base-url: ${BACKEND_BASE_URL}
    frontend-base-url: ${FRONTEND_BASE_URL}

  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

  minio:
    endpoint: ${MINION_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    buckets:
      - kundalik
      - other
      - icons

  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      username: ${TELEGRAM_BOT_USERNAME}
      webhook-path: ${TELEGRAM_BOT_PATH}
      chat-id: ${TELEGRAM_CHAT_ID}
      channel-id: ${TELEGRAM_BOT_CHANNEL}

  eskiz:
    api:
      url: ${ESKIZ_URL}
      email: ${ESKIZ_EMAIL}
      token: ${ESKIZ_TOKEN}
    sms:
      text: ${ESKIZ_SMS_TEXT}
    test-mode: true # This flag enables test mode for Eskiz SMS sending

  weather:
    api-keys:
      - ${WEATHER_API_KEY_1}
      - ${WEATHER_API_KEY_2}
    base-url: ${WEATHER_BASE_URL:https://api.weatherapi.com/v1}
    endpoints:
      forecast: /forecast.json
      search: /search.json
    default-days: ${WEATHER_DEFAULT_DAYS}
    default-city: ${WEATHER_DEFAULT_CITY}

  prayer:
    base-url: ${PRAYER_BASE_URL:https://islomapi.uz/api}
    endpoints:
      week: /present/week
      day: /present/day
    default-city: ${PRAYER_DEFAULT_CITY}

  currency:
    base-url: ${CURRENCY_API_URL:https://cbu.uz/uz/arkhiv-kursov-valyut}
    endpoints:
      all-rates: /json/
#  prayer:
#    api-week-url: ${PRAYER_WEEK_API_URL}
#    api-day-url: ${PRAYER_DAY_API_URL}
#    default-city: ${PRAYER_DEFAULT_CITY}
#
#  currency:
#    api-url: ${CURRENCY_API_URL}
#    api-key: ${CURRENCY_API_KEY}
